name: Daily Price Scraper

on:
  schedule:
    - cron: '0 11 * * *'  # 6 AM Colombia Time '0 11 * * *' 
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para obtener el historial completo y poder hacer un 'commit'.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraping script
        run: python web_scraping_haceb.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add consolidated_prices.csv
          git commit -m "chore(data): Update daily price report" || true
          git push